# Global options
foreground = yes
debug = 5
syslog = no
output = /dev/stdout

setuid = clnstrt

# be verbose in dev
debug = info

# no services by default on dev, but we need to fake on for stunnel to start
[Dummy]
client = yes
accept = 8000
connect = 10.0.0.1:5506
ciphers = PSK
PSKsecrets = /etc/stunnel/secrets/dummy




