# Global options
foreground = yes
debug = 5
syslog = no
output = /dev/stdout

setuid = clnstrt

debug = err

# off-query postgres at moji
[OFFQueryPostgres]
client = yes
accept = 
connect = 10.0.0.1:5506
ciphers = PSK
PSKsecrets = /etc/stunnel/secrets/dummy

# shared services postgres on scaleway
[OffPostgres]
client = yes
accept = 5432
connect = 151.115.132.10
ciphers = PSK
PSKsecrets = /etc/stunnel/secrets/off-postgres-psk.txt


