{
 "title": "Alerts",
 "description": "Dashboard showing Prometheus Alerts (both pending and firing) for alerts adjustment and debugging",
 "tags": [
  "prometheus",
  "alerts"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance:",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,instance)"
    }
   },
   {
    "name": "alertname",
    "label": "Alert:",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,alertname)"
    }
   },
   {
    "name": "alertstate",
    "label": "State:",
    "query": {
     "query": "label_values(ALERTS, alertstate)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Alerts count over time",
   "type": "graph",
   "description": "Alerts count over time grouped by app and environment",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Firing (+)   /  Pending (-)  " }
   ],
   "targets": [
    {
     "expr": "ALERTS{instance=~\"$instance\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"}",
     "legendFormat": "{{alertname}} - {{app}}-{{env}} - {{alertstate}}"
    },
    { "expr": "1", "legendFormat": "help_series_x_axes_in_center" }
   ]
  },
  {
   "title": "Current alerts",
   "type": "table",
   "description": "Current alerts in 'firing' state.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ALERTS{instance=~\"$instance\",alertname=~\"$alertname\", alertstate=~\"firing|pending\"}"
    }
   ]
  },
  {
   "title": "Alerts history",
   "type": "table",
   "description": "History of alerts that happened on OFF infrastructure",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes( ALERTS_FOR_STATE{instance=~\"$instance\",alertname=~\"$alertname\",alertstate!=\"pending\",severity!=\"warning\"}[$__range] ) + 1"
    }
   ]
  },
  {
   "title": "Warnings history",
   "type": "table",
   "description": "Shows how many times was particular alert started in a defined time range. Alert can be started either directly as `firing` or as a `pending`. Pending alerts wait for a defined time before it flips to a `firing` alert. This is specified with the `FOR` clause in a Prometheus `rules` file.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes( ALERTS_FOR_STATE{instance=~\"$instance\",alertname=~\"$alertname\", severity=\"warning\"}[$__range] ) + 1"
    }
   ]
  }
 ]
}