{
 "title": "HTTP Probes",
 "tags": [
  "http",
  "probes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Probes (instant)",
   "type": "gauge",
   "description": "HTTP Probes of OpenFoodFacts services",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Probes (history)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Response HTTP status codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Response latencies",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance)(probe_http_duration_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}