{
 "title": "Nodes",
 "description": "Dashboard to get an overview of one server",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_boot_time_seconds{env=~\"$env\"}, job)"
    }
   },
   { "name": "env", "label": "env", "query": { "query": "label_values(env)" } },
   { "name": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_boot_time_seconds{env=~\"$env\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg by(instance) (node_load5{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}), \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m])) * 100), \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Overall",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m]))/count(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})*100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by(instance) ((node_memory_MemTotal_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"} - node_memory_MemFree_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"} - node_memory_Buffers_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"} - node_memory_Cached_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})/node_memory_MemTotal_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}), \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Overall",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}) - sum(node_memory_MemFree_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}) - sum(node_memory_Buffers_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}) - sum(node_memory_Cached_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})) / sum(node_memory_MemTotal_bytes{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})) * 100"
    }
   ]
  },
  {
   "title": "Network Bytes Received/Transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "node_network_receive_bytes_total"
    },
    {
     "expr": "-1 * sum(rate(node_network_transmit_bytes_total{device!~\"lo\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m])) ",
     "legendFormat": "node_network_transmit_bytes_total"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "File Descriptor Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(node_filefd_allocated/node_filefd_maximum{job=~\"$job\",env=~\"$env\", instance=~\"$instance.*\"}, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!='', instance=~\"$instance.*\"} / node_filesystem_size_bytes",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  }
 ]
}