{
 "title": "Prometheus",
 "description": "Dashboard for monitoring of Prometheus v2.x.x",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Header instance info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Total count of time series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{app=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Actual head block length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time - prometheus_tsdb_head_min_time"
    }
   ]
  },
  { "title": "Main info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Query elapsed time | 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Head series created/deleted in 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(prometheus_tsdb_head_series_created_total[5m])) by (instance)",
     "legendFormat": "created on {{ instance }}"
    },
    {
     "expr": "sum(delta(prometheus_tsdb_head_series_removed_total[5m])) by (instance) * -1",
     "legendFormat": "removed on {{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_target_scrapes_exceeded_sample_limit_total[5m])",
     "legendFormat": "exceeded_sample_limit on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m])",
     "legendFormat": "duplicate_timestamp on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_target_scrapes_sample_out_of_bounds_total[5m])",
     "legendFormat": "out_of_bounds on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_target_scrapes_sample_out_of_order_total[5m])",
     "legendFormat": "out_of_order on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_rule_evaluation_failures_total[5m])",
     "legendFormat": "rule_evaluation_failure on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_tsdb_compactions_failed_total[5m])",
     "legendFormat": "tsdb_compactions_failed on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_tsdb_reloads_failures_total[5m])",
     "legendFormat": "tsdb_reloads_failures on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_not_found[5m])",
     "legendFormat": "head_series_not_found on {{ instance }}"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total[5m])) by (instance)",
     "legendFormat": "evaluator_iterations_missed on {{ instance }}"
    },
    {
     "expr": "increase(prometheus_evaluator_iterations_skipped_total[5m])",
     "legendFormat": "evaluator_iterations_skipped on {{ instance }}"
    }
   ]
  },
  { "title": "Scrape & rule duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Scrape delay (counts with 1m & 15s scrape intervals)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{instance=\"$instance\",quantile=\"0.99\",}",
     "legendFormat": "interval | {{interval}}"
    }
   ]
  },
  {
   "title": "Rule evaulation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_rule_evaluation_duration_seconds{instance=\"$instance\",}) by (instance, quantile)",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  { "title": "Requests & queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_http_request_duration_seconds_count{instance=\"$instance\",}[5m])) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} "
    }
   ]
  },
  {
   "title": "Request duration per handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(sum(prometheus_http_request_duration_seconds_count{instance=\"$instance\",}) by (instance, handler, quantile)) by (instance, handler) > 0",
     "legendFormat": "{{ handler }} "
    }
   ]
  },
  {
   "title": "Response size by handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, prometheus_http_response_size_bytes_bucket{instance=\"$instance\",})",
     "legendFormat": "{{ handler }} "
    }
   ]
  },
  {
   "title": "Cont of concurent queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_engine_queries{instance=\"$instance\",}) by (instance, handler)",
     "legendFormat": "Current count "
    },
    {
     "expr": "sum(prometheus_engine_queries_concurrent_max{instance=\"$instance\",}) by (instance, handler)",
     "legendFormat": "Max count"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Alert queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_notifications_queue_capacity{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Alert queue capacity "
    },
    {
     "expr": "sum(prometheus_notifications_queue_length{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Alert queue size on "
    }
   ]
  },
  {
   "title": "Count of discovered alertmanagers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_notifications_alertmanagers_discovered{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Checkpoint chunks written/s"
    }
   ]
  },
  {
   "title": "Alerting errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(prometheus_notifications_dropped_total{instance=\"$instance\",}[5m])) by (instance) > 0",
     "legendFormat": "notifications_dropped on {{ instance }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{rule_type=\"alerting\",instance=\"$instance\",}[5m])) by (rule_type,instance) > 0",
     "legendFormat": "rule_evaluation_failures on {{ instance }}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Service discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Kubernetes SD sync count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_sync_length_seconds{scrape_job=~\"kube.*\", quantile=\"0.99\",}",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Service discovery errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$instance\",}[5m])) by (instance)",
     "legendFormat": "exceeded_sample_limit on {{ instance }}"
    },
    {
     "expr": "sum(increase(prometheus_sd_file_read_errors_total{instance=\"$instance\",}[5m])) by (instance) ",
     "legendFormat": "sd_file_read_error on {{ instance }}"
    }
   ]
  },
  { "title": "TSDB stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Reloaded block from disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{instance=\"$instance\",}[10m])",
     "legendFormat": "Reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{instance=\"$instance\",}[10m])",
     "legendFormat": "Failed Reloads"
    }
   ]
  },
  {
   "title": "Loaded data blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=\"$instance\",}",
     "legendFormat": "Loaded data blocks"
    }
   ]
  },
  {
   "title": "Time series total count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{instance=\"$instance\",}",
     "legendFormat": "Time series count"
    }
   ]
  },
  {
   "title": "Samples Appended per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$instance\",}[5m])",
     "legendFormat": "samples/s {{instance}}"
    }
   ]
  },
  { "title": "Head block stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Head chunks count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Head chunk count"
    }
   ]
  },
  {
   "title": "Length of head block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_max_time{instance=\"$instance\",}) by (instance) - min(prometheus_tsdb_head_min_time{instance=\"$instance\",}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Head Chunks Created/Deleted per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_chunks_created_total{instance=\"$instance\",}[5m])) by (instance)",
     "legendFormat": "created on {{ instance }}"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_head_chunks_removed_total{instance=\"$instance\",}[5m])) by (instance) * -1",
     "legendFormat": "deleted on {{ instance }}"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{instance=\"$instance\",}",
     "legendFormat": "Min"
    },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    {
     "expr": "prometheus_tsdb_head_max_time{instance=\"$instance\",}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Data maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Compaction duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_sum{instance=\"$instance\",}[10m])",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{instance=\"$instance\",}[10m])"
    }
   ]
  },
  {
   "title": "Go Garbage collection duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_gc_duration_seconds{instance=\"$instance\",}) by (instance, quantile)",
     "legendFormat": "{{ quantile }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "WAL truncate duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_truncate_duration_seconds{instance=\"$instance\", quantile=\"0.99\",}",
     "legendFormat": "Latency | 99th percentile"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{instance=\"$instance\",}[10m])",
     "legendFormat": "Corruptions"
    }
   ]
  },
  {
   "title": "WAL fsync duration seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$instance\",}) by (instance, quantile)",
     "legendFormat": "{{ quantile }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{instance=\"$instance\",}[10m])",
     "legendFormat": "Compactions"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{instance=\"$instance\",}[10m])",
     "legendFormat": "Failed Compactions"
    }
   ]
  },
  {
   "title": "Compactions Triggered/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_triggered_total[10m])",
     "legendFormat": "Compactions"
    }
   ]
  },
  { "title": "RAM&CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Total resident memory - {{instance}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=\"$instance\",}) by (instance)",
     "legendFormat": "Total llocated bytes - {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$instance\",}[5m])",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$instance\",}[5m])) by (instance)",
     "legendFormat": "CPU/s"
    }
   ]
  },
  { "title": "Contrac errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Net errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",}[5m])) by (dialer_name,reason) / 5 > 0",
     "legendFormat": "{{dialer_name}} | {{reason}}"
    }
   ]
  }
 ]
}