metrics: []
# - name: openfoodfacts_query_count
#   path: "{ .count }"
#   help: Count of elements returned in Open Food Facts API query

headers:
  content-Type: "application/json"
  # user-agent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.3"
