apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prom
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: ElasticSearch (Metrics)
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[metrics-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70

  - name: ElasticSearch (Logs)
    type: elasticsearch
    uid: elasticsearch_logs
    access: proxy
    url: http://elasticsearch:9200
    database: "[logs-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: ${INFLUXDB_DB}
    url: http://influxdb:8086
    editable: true
    basicAuth: true
    basicAuthUser: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_ADMIN_PASSWORD}

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      search:
        datasourceUid: elasticsearch_logs
        filters:
        - id: service-name
          operator: "="
          scope: resource
          tag: service.name
        - id: span-name
          operator: "="
          scope: span
          tag: name
        hide: false
      serviceMap:
        datasourceUid: prom
      tracesToLogsV2:
        customQuery: true
        datasourceUid: elasticsearch_logs
        query: 'tags | trace_id = "${__trace.traceId}"'
        tags:
        - key: service.name
          value: service_name
      tracesToProfiles:
        datasourceUid: grafana
